# Generated by Django 5.1.4 on 2024-12-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("useranswer", models.TextField(default="")),
                (
                    "question_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
            ],
        ),
    ]
